import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { getGlobalData } from "@/lib/api/getGlobalData";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const global = await getGlobalData();
  console.log(global);

  const faviconUrl = global.favicon?.formats?.small?.url;
  const fullFaviconUrl = faviconUrl?.startsWith("http")
    ? faviconUrl
    : `${process.env.NEXT_PUBLIC_API_URL?.replace("/api", "")}${faviconUrl}`;

  return {
    title: global.siteName,
    description: global.siteDescription,
    icons: {
      icon: fullFaviconUrl,
    },
  };
}

const font = Space_Grotesk({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" className={font.className}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
