import { Space_Grotesk } from "next/font/google";
import Navbar from "@/components/layout/Navbar";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export async function generateMetadata(): Promise<Metadata> {
//   const global = await getGlobalData();
//   console.log(global);

//   const faviconUrl = global.favicon?.formats?.small?.url;
//   const fullFaviconUrl = faviconUrl?.startsWith("http")
//     ? faviconUrl
//     : `${process.env.NEXT_PUBLIC_API_URL?.replace("/api", "")}${faviconUrl}`;

//   return {
//     title: global.siteName,
//     description: global.siteDescription,
//     icons: {
//       icon: fullFaviconUrl,
//     },
//   };
// }

const font = Space_Grotesk({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" className={font.className}>
      <body className={`antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
