export const teams = [
  {
    team: "Wróblowianka Kraków",
    points: 21,
    matches: 7,
    wins: 7,
    draws: 0,
    losses: 0,
    goals: "28:5",
    form: ["W", "W", "W", "W"],
  },
  {
    team: "Iskra Zakrzów",
    points: 21,
    matches: 7,
    wins: 7,
    draws: 0,
    losses: 0,
    goals: "21:6",
    form: ["W", "W", "W", "W"],
  },
  {
    team: "LKS Śledziejowice",
    points: 15,
    matches: 7,
    wins: 5,
    draws: 0,
    losses: 2,
    goals: "26:15",
    form: ["W", "L", "L", "W"],
  },
  {
    team: "Wolni Kłaj",
    points: 13,
    matches: 7,
    wins: 4,
    draws: 1,
    losses: 2,
    goals: "16:21",
    form: ["W", "L", "D", "W", "L"],
  },
  {
    team: "Zjednoczeni Branice",
    points: 12,
    matches: 7,
    wins: 4,
    draws: 0,
    losses: 3,
    goals: "17:16",
    form: ["W", "L", "W", "W"],
  },
  {
    team: "Gdovia Gdów",
    points: 11,
    matches: 7,
    wins: 3,
    draws: 2,
    losses: 2,
    goals: "18:8",
    form: ["L", "L", "D", "W", "D"],
  },
  {
    team: "Górnik Wieliczka",
    points: 10,
    matches: 7,
    wins: 3,
    draws: 1,
    losses: 3,
    goals: "30:20",
    form: ["L", "W", "L", "L"],
  },
  {
    team: "Węgrzcanka Węgrzce Wielkie",
    points: 10,
    matches: 7,
    wins: 3,
    draws: 1,
    losses: 3,
    goals: "18:17",
    form: ["W", "L", "W", "D"],
  },
  {
    team: "Gwiazda Brzegi",
    points: 10,
    matches: 7,
    wins: 3,
    draws: 1,
    losses: 3,
    goals: "14:22",
    form: ["D", "W", "W", "L", "W"],
  },
  {
    team: "Wiarusy Igołomia",
    points: 9,
    matches: 7,
    wins: 3,
    draws: 0,
    losses: 4,
    goals: "16:18",
    form: ["L", "W", "L", "L", "L"],
  },
  {
    team: "Błękitni Bodzanów",
    points: 7,
    matches: 7,
    wins: 2,
    draws: 1,
    losses: 4,
    goals: "16:20",
    form: ["D", "L", "W", "L", "W"],
  },
];
